CREATE SCHEMA IF NOT EXISTS open_data;

CREATE OR REPLACE VIEW open_data.tmcs_count_data AS (
  SELECT
    d."COUNT_INFO_ID" AS count_id,
    cim."COUNT_DATE"::DATE + d."COUNT_TIME"::TIME - '15 minutes'::interval AS time_start,
    cim."COUNT_DATE"::DATE + d."COUNT_TIME"::TIME AS time_end,
    d."N_CARS_R" AS sb_cars_r,
    d."N_CARS_T" AS sb_cars_t,
    d."N_CARS_L" AS sb_cars_l,
    d."S_CARS_R" AS nb_cars_r,
    d."S_CARS_T" AS nb_cars_t,
    d."S_CARS_L" AS nb_cars_l,
    d."E_CARS_R" AS wb_cars_r,
    d."E_CARS_T" AS wb_cars_t,
    d."E_CARS_L" AS wb_cars_l,
    d."W_CARS_R" AS eb_cars_r,
    d."W_CARS_T" AS eb_cars_t,
    d."W_CARS_L" AS eb_cars_l,
    d."N_TRUCK_R" AS sb_truck_r,
    d."N_TRUCK_T" AS sb_truck_t,
    d."N_TRUCK_L" AS sb_truck_l,
    d."S_TRUCK_R" AS nb_truck_r,
    d."S_TRUCK_T" AS nb_truck_t,
    d."S_TRUCK_L" AS nb_truck_l,
    d."E_TRUCK_R" AS wb_truck_r,
    d."E_TRUCK_T" AS wb_truck_t,
    d."E_TRUCK_L" AS wb_truck_l,
    d."W_TRUCK_R" AS eb_truck_r,
    d."W_TRUCK_T" AS eb_truck_t,
    d."W_TRUCK_L" AS eb_truck_l,
    d."N_BUS_R" AS sb_bus_r,
    d."N_BUS_T" AS sb_bus_t,
    d."N_BUS_L" AS sb_bus_l,
    d."S_BUS_R" AS nb_bus_r,
    d."S_BUS_T" AS nb_bus_t,
    d."S_BUS_L" AS nb_bus_l,
    d."E_BUS_R" AS wb_bus_r,
    d."E_BUS_T" AS wb_bus_t,
    d."E_BUS_L" AS wb_bus_l,
    d."W_BUS_R" AS eb_bus_r,
    d."W_BUS_T" AS eb_bus_t,
    d."W_BUS_L" AS eb_bus_l,
    d."N_PEDS" AS nx_peds,
    d."S_PEDS" AS sx_peds,
    d."E_PEDS" AS ex_peds,
    d."W_PEDS" AS wx_peds,
    d."N_BIKE" AS nx_bike,
    d."S_BIKE" AS sx_bike,
    d."E_BIKE" AS ex_bike,
    d."W_BIKE" AS wx_bike,
    d."N_OTHER" AS nx_other,
    d."S_OTHER" AS sx_other,
    d."E_OTHER" AS ex_other,
    d."W_OTHER" AS wx_other
  FROM "TRAFFIC"."DET" d
  JOIN "TRAFFIC"."COUNTINFOMICS" cim USING ("COUNT_INFO_ID")
  ORDER BY d."COUNT_INFO_ID" ASC, d."COUNT_TIME" ASC
);
