CREATE SCHEMA IF NOT EXISTS open_data;

CREATE OR REPLACE VIEW open_data.tmcs_count_data AS (
  SELECT
    "COUNT_INFO_ID" AS count_id,
    "COUNT_TIME" - '15 minutes'::interval AS time_start,
    "COUNT_TIME" AS time_end,
    "N_CARS_R" AS sb_cars_r,
    "N_CARS_T" AS sb_cars_t,
    "N_CARS_L" AS sb_cars_l,
    "S_CARS_R" AS nb_cars_r,
    "S_CARS_T" AS nb_cars_t,
    "S_CARS_L" AS nb_cars_l,
    "E_CARS_R" AS wb_cars_r,
    "E_CARS_T" AS wb_cars_t,
    "E_CARS_L" AS wb_cars_l,
    "W_CARS_R" AS eb_cars_r,
    "W_CARS_T" AS eb_cars_t,
    "W_CARS_L" AS eb_cars_l,
    "N_TRUCK_R" AS sb_truck_r,
    "N_TRUCK_T" AS sb_truck_t,
    "N_TRUCK_L" AS sb_truck_l,
    "S_TRUCK_R" AS nb_truck_r,
    "S_TRUCK_T" AS nb_truck_t,
    "S_TRUCK_L" AS nb_truck_l,
    "E_TRUCK_R" AS wb_truck_r,
    "E_TRUCK_T" AS wb_truck_t,
    "E_TRUCK_L" AS wb_truck_l,
    "W_TRUCK_R" AS eb_truck_r,
    "W_TRUCK_T" AS eb_truck_t,
    "W_TRUCK_L" AS eb_truck_l,
    "N_BUS_R" AS sb_bus_r,
    "N_BUS_T" AS sb_bus_t,
    "N_BUS_L" AS sb_bus_l,
    "S_BUS_R" AS nb_bus_r,
    "S_BUS_T" AS nb_bus_t,
    "S_BUS_L" AS nb_bus_l,
    "E_BUS_R" AS wb_bus_r,
    "E_BUS_T" AS wb_bus_t,
    "E_BUS_L" AS wb_bus_l,
    "W_BUS_R" AS eb_bus_r,
    "W_BUS_T" AS eb_bus_t,
    "W_BUS_L" AS eb_bus_l,
    "N_PEDS" AS nx_peds,
    "S_PEDS" AS sx_peds,
    "E_PEDS" AS ex_peds,
    "W_PEDS" AS wx_peds,
    "N_BIKE" AS nx_bike,
    "S_BIKE" AS sx_bike,
    "E_BIKE" AS ex_bike,
    "W_BIKE" AS wx_bike,
    "N_OTHER" AS nx_other,
    "S_OTHER" AS sx_other,
    "E_OTHER" AS ex_other,
    "W_OTHER" AS wx_other
  FROM "TRAFFIC"."DET"
  ORDER BY "COUNT_INFO_ID" ASC, "COUNT_TIME" ASC
);
