CREATE DATABASE airflow;
CREATE USER airflow WITH NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD NULL;
ALTER ROLE airflow WITH PASSWORD ':airflowPassword';
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
